mutation CreateAddress($addressFields: AddressInput) {
  createAddress(fields: $addressFields) {
    cacheId
    addresses: address {
      addressId: id
      addressType
      addressName
      city
      complement
      country
      neighborhood
      number
      postalCode
      geoCoordinates
      receiverName
      reference
      state
      street
    }
  }
}
