query Addresses @context(scope: "private") {
  profile {
    addresses: address {
      addressId: id
      addressType
      addressName
      city
      complement
      country
      neighborhood
      number
      postalCode
      receiverName
      reference
      state
      street
    }
  }
}
