query Payments @context(scope: "private") {
  profile {
    cacheId
    payments {
      id
      paymentSystem
      cardNumber
      address {
        addressId: id
        addressName
        addressType
        city
        complement
        country
        neighborhood
        number
        postalCode
        state
        street
      }
    }
  }
}
