mutation RedefinePassword($email: String!, $currentPassword: String!, $newPassword: String!) {
  redefinePassword(email: $email, currentPassword: $currentPassword, newPassword: $newPassword, vtexIdVersion:"myaccount-ui")
}