mutation UpdateProfile($profile: ProfileInput) {
  updateProfile(fields: $profile) {
    cacheId
    firstName
    lastName
    birthDate
    gender
    homePhone
    businessPhone
    document
    email
    tradeName
    corporateName
    corporateDocument
    stateRegistration
    isCorporate
  }
}
