mutation UpdateAddress($addressId: String, $address: AddressInput) {
  updateAddress(id: $addressId, fields: $address) {
    addressId: id
    addressType
    city
    complement
    country
    neighborhood
    number
    postalCode
    geoCoordinates: geoCoordinate
    receiverName
    reference
    state
    street
  }
}
