mutation UpdateAddress($addressId: String, $addressFields: AddressInput) {
  updateAddress(id: $addressId, fields: $addressFields)
    @context(provider: "vtex.store-graphql") {
    cacheId
    addresses: address {
      addressId: id
      addressType
      addressName
      city
      complement
      country
      neighborhood
      number
      postalCode
      geoCoordinates
      receiverName
      reference
      state
      street
    }
  }
}
